artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://drive.google.com/file/d/1wX1NGvUfyl8k-_Bh5xF4NBvdv5H53Qaq/view?usp=sharing
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.h5
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.h5
  

training:
  root_dir: artifacts\data_ingestion\Data-CS-DVC\training_data
  Med_train: artifacts\data_ingestion\Data-CS-DVC\training_data\Med_train
  Cover_train: artifacts\data_ingestion\Data-CS-DVC\training_data\Cover_train
  Med_val: artifacts\data_ingestion\Data-CS-DVC\validation_data\Med_val
  Cover_val: artifacts\data_ingestion\Data-CS-DVC\validation_data\Cover_val
  trained_model_path: artifacts/training/model.h5
